### ISSUE TITLE
Processing PDB with >2 chains

### ISSUE THREAD

**Issue by josef0731** [Fraternalilab/POPScomp#4]
@jkleinj I noticed the shiny server seems not to be able to process PDB inputs with more than 2 chains - it always throw a red text complaining about Error and ask me to contact the app developer. PDB inputs with exactly 2 chains seem to work fine with Exit code = 0. *For example,* **5td5** (which has 2 chains) works, but **5sww** (8 chains) does not [*now both of these are protein-DNA complexes but that shouldn't be the problem, as the output on the protein chains should still be returned*].

I had a look and I think the issue is in the `popscompR` function in the R package - I point these lines out and with the suggestions I use, at least the function does not throw error and did write contents to an output file - please check and see whether these produce outputs without unexpected errors/behaviours?

https://github.com/Fraternalilab/POPScomp/blob/5371a2c4e6306ec34a2cb5fe6e0e79f099c1d9be/POPSR/R/popscomp.R#L91

should read `return(chainpair.files[[x]])` - the current version makes it a list-of-list situation that the code downstream can't work with.

https://github.com/Fraternalilab/POPScomp/blob/5371a2c4e6306ec34a2cb5fe6e0e79f099c1d9be/POPSR/R/popscomp.R#L134

(*and all occurrences of `length(dim(pair.cmbn)[2])`*) should read `dim(pair.cmbn)[2]` only (with `length` it would always be 1 wouldn't it??)

Joseph

**Comment by jkleinj** [comment]
Thanks Joseph,
your observations were spot-on, both errors have been corrected now.
Additionally I have added 'wait = TRUE' arguments to system calls to make sure 'popscompR'  sees all the output files that are created by those calls. The corrected version is 3.1.6.

  Jens
